repos:
  - repo: "https://github.com/psf/black"
    rev: "25.11.0"
    hooks:
      - id: black

  - repo: "https://github.com/PyCQA/isort"
    rev: "7.0.0"
    hooks:
      - id: isort

  - repo: "https://github.com/pycqa/flake8"
    rev: "7.3.0"
    hooks:
      - id: flake8

  - repo: "https://github.com/PyCQA/autoflake"
    rev: "v2.3.1"
    hooks:
      - id: autoflake
        args: ["--remove-all-unused-imports", "--recursive", "--in-place"]

  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: "v1.18.2"
    hooks:
      - id: mypy

  - repo: "https://github.com/PyCQA/bandit"
    rev: "1.8.6"
    hooks:
      - id: bandit
